#!/bin/bash

cd /home/pi/src

while [ ! -e /dev/spidev0.0 ]; do
    echo "Wachten tot 't SPI device bestaat..."
    sleep 5
done

echo "$0 gestart"

(while true; do
    
    ./regenboogje 120
    sleep 1
    ./pixelfades 120
    sleep 1

done) | ./mqtt_events | ./mqtt_status | ./broken_leds | ./ledspace    
    
